import type { Metadata } from "next";
import "../globals.css";
import NavBar from "../components/common/nav";
import GlobalProvider from "@/context/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("Layout on server");
  return (
    <html lang="en">
      <body>
        <section>
          <GlobalProvider>
            <NavBar />
          </GlobalProvider>
        </section>
        {children}
      </body>
    </html>
  );
}
